project_identifier_env: CROWDIN_PROJECT_ID
api_key_env: CROWDIN_API_KEY
base_path: ./
preserve_hierarchy: true
files:
  - source: /docs/*.md
    translation: /website/translated_docs/%locale%/%original_file_name%
    languages_mapping:
      locale:
        ja: ja
        de: de
        es-ES: es-ES
        fr: fr
        pt-PT: pt-PT

  - source: /docs/assets/en/**/*.png
    translation: /docs/assets/%two_letters_code%/**/%original_file_name%
  - &ref_languages_mapping
    source: /website/i18n/en.json
    translation: /website/i18n/%locale%.json
    languages_mapping: []
