project_identifier_env: CROWDIN_PROJECT_ID
api_key_env: CROWDIN_API_KEY
base_path: "./"
preserve_hierarchy: true

files:
  -
    source: /docs/*.md
    translation: '/website/translated_docs/%locale%/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'es-ES': 'es-ES'
        'fr': 'fr'

  -
    source: '/docs/assets/**/*.png'
    translation: '/website/translated_docs/%locale%/assets/**/%original_file_name%'
    languages_mapping: *anchor

  -
    source: '/website/i18n/en.json'
    translation: '/website/i18n/%locale%.json'
    languages_mapping: *anchor
