project_identifier_env: CROWDIN_PROJECT_ID
api_key_env: CROWDIN_API_KEY
base_path: ./
preserve_hierarchy: true
append_commit_message: false
files:
  - source: /docs/*.md
    translation: /website/translated_docs/%two_letters_code%/%original_file_name%
  - source: /docs/assets/en/**/*.png
    translation: /docs/assets/%two_letters_code%/**/%original_file_name%
  - source: /website/i18n/en.json
    translation: /website/i18n/%two_letters_code%.json
