var command = 'ABORT|Abs|ACCEPT|ACCUMULATE|Activated|Active transaction|ADD DATA SEGMENT|ADD RECORD|ADD SUBRECORD|Add to date|ADD TO SET|ADJUST BLOBS CACHE PRIORITY|'+
'ADJUST INDEX CACHE PRIORITY|ADJUST TABLE CACHE PRIORITY|After|ALERT|ALL RECORDS|ALL SUBRECORDS|APPEND DATA TO PASTEBOARD|Append document|APPEND MENU ITEM|'+
'APPEND TO ARRAY|APPEND TO LIST|Application file|Application type|Application version|APPLY TO SELECTION|APPLY TO SUBSELECTION|APPLY XSLT TRANSFORMATION|Arctan|'+
'ARRAY BLOB|ARRAY BOOLEAN|ARRAY DATE|ARRAY INTEGER|ARRAY LONGINT|ARRAY OBJECT|ARRAY PICTURE|ARRAY POINTER|ARRAY REAL|ARRAY STRING|ARRAY TEXT|ARRAY TIME|'+
'ARRAY TO COLLECTION|ARRAY TO LIST|ARRAY TO SELECTION|ARRAY TO STRING LIST|ASSERT|Asserted|AUTHENTICATE WEB SERVICE|Average|BACKUP|BASE64 DECODE|BASE64 ENCODE|'+
'BEEP|Before|Before selection|Before subselection|Begin SQL|BEST OBJECT SIZE|BLOB PROPERTIES|BLOB size|BLOB TO DOCUMENT|BLOB to integer|BLOB to list|BLOB to longint|'+
'BLOB TO PICTURE|Character code|BLOB to print settings|BLOB to real|BLOB to text|BLOB TO USERS|BLOB TO VARIABLE|Bool|BOOLEAN ARRAY FROM SET|BREAK LEVEL|BRING TO FRONT|'+
'BUILD APPLICATION|BUTTON TEXT|Cache info|CALL FORM|CALL PROCESS|CALL SUBFORM CONTAINER|CALL WEB SERVICE|CALL WORKER|CANCEL|CANCEL TRANSACTION|Caps lock down|'+
'CHANGE CURRENT USER|CHANGE LICENSES|CHANGE PASSWORD|Change string|code|CHECK LOG FILE|CHECK MEMORY LEAKS|Choose|CLEAR LIST|CLEAR NAMED SELECTION|'+
'CLEAR PASTEBOARD|CLEAR SEMAPHORE|Form|CLEAR SET|CLEAR VARIABLE|Clickcount|CLOSE DOCUMENT|CLOSE PRINTING JOB|CLOSE RESOURCE FILE|CLOSE WINDOW|COLLECTION TO ARRAY|'+
'collection length|COMBINE PICTURES|Command name|Field name|Compact data file|COMPONENT LIST|COMPRESS BLOB|COMPRESS PICTURE|COMPRESS PICTURE FILE|CONFIRM|Contextual click|'+
'Convert case|CONVERT COORDINATES|CONVERT FROM TEXT|Convert path POSIX to system|Convert path system to POSIX|CONVERT PICTURE|Convert to text|COPY ARRAY|COPY BLOB|'+
'COPY DOCUMENT|Copy list|COPY NAMED SELECTION|COPY SET|Cos|Count in array|Count list items|Count menu items|Count menus|Count parameters|Count screens|Count tasks|'+
'Count user processes|Count users|CREATE ALIAS|CREATE DATA FILE|Create document|CREATE EMPTY SET|Create entity selection|CREATE FOLDER|CREATE INDEX|Create menu|'+
'CREATE RECORD|CREATE RELATED ONE|Create resource file|CREATE SELECTION FROM ARRAY|CREATE SET|CREATE SET FROM ARRAY|CREATE SUBRECORD|CREATE THUMBNAIL|'+
'CREATE USER FORM|Current client authentication|Current date|Current default table|Current form name|Current form page|Current form table|Current form window|'+
'Current machine|Current machine owner|Current method name|Current method path|Current process|Current process name|Current system user|Current time|Current user|'+
'CUT NAMED SELECTION|C_BLOB|C_BOOLEAN|C_COLLECTION|C_DATE|C_GRAPH|C_INTEGER|C_LONGINT|C_OBJECT|C_PICTURE|C_POINTER|C_REAL|C_STRING|C_TEXT|C_TIME|Data file|'+
'DATA SEGMENT LIST|Database event|Day number|Day of|Deactivated|Dec|DECODE|DECRYPT BLOB|DEFAULT TABLE|DELAY PROCESS|DELETE DOCUMENT|DELETE FOLDER|'+
'DELETE FROM ARRAY|DELETE FROM BLOB|DELETE FROM LIST|DELETE INDEX|DELETE LISTBOX COLUMN|DELETE LISTBOX ROW|DELETE MENU ITEM|DELETE RECORD|DELETE RESOURCE|'+
'DELETE SELECTION|Delete string|DELETE SUBRECORD|DELETE USER|DELETE USER FORM|DESCRIBE QUERY EXECUTION|DIALOG|DIFFERENCE|DISABLE BUTTON|DISABLE MENU ITEM|'+
'DISPLAY NOTIFICATION|DISPLAY RECORD|DISPLAY SELECTION|Displayed line number|DISTINCT ATTRIBUTE PATHS|DISTINCT ATTRIBUTE VALUES|DISTINCT VALUES|Document creator|'+
'DOCUMENT LIST|DOCUMENT TO BLOB|Document to text|Document type|DOM Append XML child node|DOM Append XML element|DOM CLOSE XML|DOM Count XML attributes|'+
'DOM Count XML elements|DOM Create XML element|DOM Create XML element arrays|DOM Create XML Ref|DOM EXPORT TO FILE|DOM EXPORT TO VAR|DOM Find XML element|'+
'DOM Find XML element by ID|DOM Get first child XML element|DOM Get last child XML element|DOM Get next sibling XML element|DOM Get parent XML element|'+
'DOM Get previous sibling XML element|DOM Get Root XML element|DOM GET XML ATTRIBUTE BY INDEX|DOM GET XML ATTRIBUTE BY NAME|DOM GET XML CHILD NODES|'+
'DOM Get XML document ref|DOM Get XML element|DOM GET XML ELEMENT NAME|DOM GET XML ELEMENT VALUE|Date|DOM Get XML information|DOM Insert XML element|DOM Parse XML source|'+
'DOM Parse XML variable|DOM REMOVE XML ATTRIBUTE|DOM REMOVE XML ELEMENT|DOM SET XML ATTRIBUTE|DOM SET XML DECLARATION|DOM SET XML ELEMENT NAME|DOM SET XML ELEMENT VALUE|'+
'DOM SET XML OPTIONS|DRAG AND DROP PROPERTIES|DRAG WINDOW|Drop position|ds|DUPLICATE RECORD|During|Dynamic pop up menu|EDIT ACCESS|EDIT FORM|EDIT FORMULA|EDIT ITEM|'+
'ENABLE BUTTON|ENABLE MENU ITEM|ENCODE|ENCRYPT BLOB|Encrypt data file|Encryption status|End selection|End SQL|End subselection|Equal pictures|ERASE WINDOW|'+
'Euro converter|EXECUTE FORMULA|EXECUTE METHOD|EXECUTE METHOD IN SUBFORM|EXECUTE ON CLIENT|Execute on server|Exp|EXPAND BLOB|EXPORT DATA|EXPORT DIF|EXPORT ODBC|'+
'EXPORT STRUCTURE|Export structure file|EXPORT SYLK|EXPORT TEXT|False|Field|FILTER EVENT|FILTER KEYSTROKE|Find in array|Find in field|Find in list|'+
'Find in sorted array|Find window|FIRST PAGE|FIRST RECORD|FIRST SUBRECORD|FLUSH BUFFERS|FLUSH CACHE|Focus object|FOLDER LIST|FONT|FONT LIST|Font name|Font number|'+
'FONT SIZE|FONT STYLE|FONT STYLE LIST|FORM Convert to dynamic|Form event|FORM FIRST PAGE|FORM Get current page|FORM GET ENTRY ORDER|FORM GET HORIZONTAL RESIZING|'+
'FORM GET NAMES|FORM GET OBJECTS|FORM GET PARAMETER|FORM GET PROPERTIES|FORM GET VERTICAL RESIZING|FORM GOTO PAGE|FORM LAST PAGE|FORM LOAD|FORM NEXT PAGE|'+
'FORM PREVIOUS PAGE|FORM SCREENSHOT|FORM SET ENTRY ORDER|FORM SET HORIZONTAL RESIZING|FORM SET INPUT|FORM SET OUTPUT|FORM SET SIZE|FORM SET VERTICAL RESIZING|'+
'FORM UNLOAD|Frontmost process|Frontmost window|GENERATE CERTIFICATE REQUEST|Generate digest|GENERATE ENCRYPTION KEYPAIR|Generate password hash|Generate UUID|'+
'Gestalt|Get 4D file|Get 4D folder|Get action info|GET ACTIVITY SNAPSHOT|Get adjusted blobs cache priority|Get adjusted index cache priority|'+
'Get adjusted table cache priority|Get alignment|GET ALLOWED METHODS|Get application info|Get assert enabled|GET AUTOMATIC RELATIONS|GET BACKUP INFORMATION|'+
'Get cache size|GET CACHE STATISTICS|Get component resource ID|Get current data source|Get current database localization|Get current printer|GET DATA SOURCE LIST|'+
'Get database localization|Get database measures|Get database parameter|Get default user|GET DOCUMENT ICON|Get document position|GET DOCUMENT PROPERTIES|'+
'Get document size|Get edited text|Get external data path|GET FIELD ENTRY PROPERTIES|GET FIELD PROPERTIES|GET FIELD RELATION|GET FIELD TITLES|Get file from pasteboard|'+
'GET FORM OBJECTS|GET FORM PARAMETER|GET FORM PROPERTIES|Get format|GET GROUP LIST|GET GROUP PROPERTIES|GET HIGHLIGHT|GET HIGHLIGHTED RECORDS|GET HTTP BODY|'+
'GET HTTP HEADER|GET ICON RESOURCE|Get indexed string|GET LAST ERROR STACK|Get last field number|Get last query path|Get last query plan|Get last table number|'+
'Get last update log path|Get license info|GET LIST ITEM|Get list item font|GET LIST ITEM ICON|GET LIST ITEM PARAMETER|GET LIST ITEM PARAMETER ARRAYS|'+
'GET LIST ITEM PROPERTIES|GET LIST PROPERTIES|GET LISTBOX ARRAYS|GET LISTBOX CELL POSITION|Get listbox column width|Get listbox information|Get listbox rows height|'+
'GET LISTBOX TABLE SOURCE|Get localized document path|Get localized string|Get locked records info|GET MACRO PARAMETER|Get memory leaks|GET MEMORY STATISTICS|'+
'Get menu bar reference|Get menu item|GET MENU ITEM ICON|Get menu item key|Get menu item mark|Get menu item method|Get menu item modifiers|Get menu item parameter|'+
'GET MENU ITEM PROPERTY|Get menu item style|GET MENU ITEMS|Get menu title|GET MISSING TABLE NAMES|GET MOUSE|Get number of listbox columns|Get number of listbox rows|'+
'GET OBJECT RECT|GET PASTEBOARD DATA|GET PASTEBOARD DATA TYPE|Get picture file name|GET PICTURE FORMATS|GET PICTURE FROM LIBRARY|GET PICTURE FROM PASTEBOARD|'+
'GET PICTURE KEYWORDS|GET PICTURE METADATA|GET PICTURE RESOURCE|Get platform interface|Get plugin access|Get pointer|Get print marker|GET PRINT OPTION|'+
'Get print preview|GET PRINTABLE AREA|GET PRINTABLE MARGIN|Get printed height|Get process activity|GET PROCESS VARIABLE|GET QUERY DESTINATION|Get query limit|'+
'GET REGISTERED CLIENTS|GET RELATION PROPERTIES|GET RESOURCE|Get resource name|Get resource properties|GET RESTORE INFORMATION|Get selected menu item parameter|'+
'GET SERIAL INFORMATION|GET SERIAL PORT MAPPING|Get SOAP info|Get string resource|GET STYLE SHEET INFO|Get subrecord key|GET SYSTEM FORMAT|Get system info|'+
'Get table fragmentation|GET TABLE PROPERTIES|GET TABLE TITLES|Get text from pasteboard|GET TEXT KEYWORDS|Get text resource|GET USER LIST|GET USER PROPERTIES|'+
'GET WEB FORM VARIABLES|Get Web Service error info|GET WEB SERVICE RESULT|GET WINDOW RECT|Get window title|GET XML ERROR|GET XSLT ERROR|GOTO AREA|GOTO OBJECT|'+
'GOTO PAGE|GOTO RECORD|GOTO SELECTED RECORD|GOTO XY|GRAPH|GRAPH SETTINGS|GRAPH TABLE|HIDE MENU BAR|HIDE PROCESS|HIDE TOOL BAR|HIDE WINDOW|HIGHLIGHT RECORDS|'+
'HIGHLIGHT TEXT|HTTP AUTHENTICATE|HTTP Get|HTTP Get certificates folder|HTTP GET OPTION|HTTP Request|HTTP SET CERTIFICATES FOLDER|HTTP SET OPTION|IDLE|IMPORT DATA|'+
'IMPORT DIF|IMPORT ODBC|IMPORT STRUCTURE|IMPORT SYLK|IMPORT TEXT|In break|In footer|In header|In transaction|INPUT FORM|INSERT IN ARRAY|INSERT IN BLOB|'+
'INSERT IN LIST|INSERT LISTBOX COLUMN|INSERT LISTBOX COLUMN FORMULA|INSERT LISTBOX ROW|INSERT MENU ITEM|Insert string|Int|INTEGER TO BLOB|INTEGRATE LOG FILE|'+
'INTEGRATE MIRROR LOG FILE|INTERSECTION|INVERT BACKGROUND|INVOKE ACTION|Is a list|Is a variable|Is compiled mode|Is data file locked|Is field number valid|'+
'Is field value Null|Is in print preview|Is in set|Is license available|Is macOS|Is new record|Is nil pointer|Is picture file|Is record loaded|Is SOAP request|'+
'Is table number valid|Is user deleted|Is waiting mouse up|Is Windows|ISO to Mac|JSON Parse|JSON PARSE ARRAY|JSON Resolve pointers|JSON Stringify|'+
'JSON Stringify array|JSON TO SELECTION|JSON Validate|Keystroke|KILL WORKER|LAST PAGE|LAST RECORD|LAST SUBRECORD|LAUNCH EXTERNAL PROCESS|LDAP LOGIN|LDAP LOGOUT|'+
'LDAP Search|LDAP SEARCH ALL|Length|Level|List item parent|List item position|LIST OF CHOICE LISTS|LIST OF STYLE SHEETS|LIST TO ARRAY|LIST TO BLOB|'+
'LIST USER FORMS|LISTBOX COLLAPSE|LISTBOX DELETE COLUMN|LISTBOX DELETE ROW|LISTBOX DELETE ROWS|LISTBOX DUPLICATE COLUMN|LISTBOX EXPAND|LISTBOX Get array|'+
'LISTBOX GET ARRAYS|LISTBOX Get auto row height|LISTBOX GET CELL COORDINATES|LISTBOX GET CELL POSITION|LISTBOX Get column formula|LISTBOX Get column width|'+
'LISTBOX Get footer calculation|LISTBOX Get footers height|LISTBOX GET GRID|LISTBOX GET GRID COLORS|LISTBOX Get headers height|LISTBOX GET HIERARCHY|'+
'LISTBOX Get information|LISTBOX Get locked columns|LISTBOX Get number of columns|LISTBOX Get number of rows|LISTBOX GET OBJECTS|LISTBOX GET PRINT INFORMATION|'+
'LISTBOX Get property|LISTBOX Get row color|LISTBOX Get row font style|LISTBOX Get row height|LISTBOX Get rows height|LISTBOX Get static columns|'+
'LISTBOX GET TABLE SOURCE|LISTBOX INSERT COLUMN|LISTBOX INSERT COLUMN FORMULA|LISTBOX INSERT ROW|LISTBOX INSERT ROWS|LISTBOX MOVE COLUMN|LISTBOX MOVED COLUMN NUMBER|'+
'LISTBOX MOVED ROW NUMBER|LISTBOX SELECT BREAK|LISTBOX SELECT ROW|LISTBOX SET ARRAY|LISTBOX SET AUTO ROW HEIGHT|LISTBOX SET COLUMN FORMULA|LISTBOX SET COLUMN WIDTH|'+
'LISTBOX SET FOOTER CALCULATION|LISTBOX SET FOOTERS HEIGHT|LISTBOX SET GRID|LISTBOX SET GRID COLOR|LISTBOX SET HEADERS HEIGHT|LISTBOX SET HIERARCHY|'+
'LISTBOX SET LOCKED COLUMNS|LISTBOX SET PROPERTY|LISTBOX SET ROW COLOR|LISTBOX SET ROW FONT STYLE|LISTBOX SET ROW HEIGHT|LISTBOX SET ROWS HEIGHT|'+
'LISTBOX SET STATIC COLUMNS|LISTBOX SET TABLE SOURCE|LISTBOX SHOW GRID|LISTBOX SORT COLUMNS|Load 4D View document|LOAD COMPRESS PICTURE FROM FILE|'+
'Load list|LOAD RECORD|LOAD SET|LOAD VARIABLES|Locked|LOCKED ATTRIBUTES|LOCKED BY|Log|LOG EVENT|Log File|LOG FILE TO JSON|LONGINT ARRAY FROM SELECTION|'+
'LONGINT TO BLOB|Lowercase|Mac to ISO|Mac to Win|Macintosh command down|Macintosh control down|Macintosh option down|MAIL Convert to MIME|MAP FILE TYPES|'+
'Match regex|Max|MAXIMIZE WINDOW|Menu bar height|Menu bar screen|Menu selected|MESSAGE|MESSAGES OFF|MESSAGES ON|Method called on error|Method called on event|'+
'METHOD Get attribute|METHOD GET ATTRIBUTES|METHOD GET CODE|METHOD GET COMMENTS|METHOD GET FOLDERS|METHOD GET MODIFICATION DATE|METHOD GET NAMES|'+
'METHOD Get path|METHOD GET PATHS|METHOD GET PATHS FORM|METHOD OPEN PATH|METHOD RESOLVE PATH|METHOD SET ACCESS MODE|METHOD SET ATTRIBUTE|METHOD SET ATTRIBUTES|'+
'METHOD SET CODE|METHOD SET COMMENTS|Milliseconds|Min|MINIMIZE WINDOW|MOBILE APP REFRESH SESSIONS|MOBILE Return selection|Mod|Modified|Modified record|'+
'MODIFY RECORD|MODIFY SELECTION|MODIFY SUBRECORD|Month of|MOVE DOCUMENT|MOVE OBJECT|MOVED LISTBOX COLUMN NUMBER|MOVED LISTBOX ROW NUMBER|MULTI SORT ARRAY|'+
'New collection|New formula|New formula from string|New list|New log file|New object|New process|New shared collection|New shared object|NEXT PAGE|NEXT RECORD|'+
'NEXT SUBRECORD|Next window|Nil|NO DEFAULT TABLE|NO TRACE|Not|NOTIFY RESOURCES FOLDER MODIFICATION|Null|Num|OB Copy|OB Get|OB GET ARRAY|OB GET PROPERTY NAMES|'+
'OB Get type|OB Is defined|OB Is empty|OB REMOVE|OB SET|OB SET ARRAY|OB SET NULL|OBJECT DUPLICATE|OBJECT Get action|OBJECT Get alignment|OBJECT Get auto spellcheck|'+
'OBJECT GET BEST SIZE|OBJECT Get border style|OBJECT Get choice list name|OBJECT Get context menu|OBJECT GET COORDINATES|OBJECT Get corner radius|'+
'OBJECT Get data source|OBJECT GET DRAG AND DROP OPTIONS|OBJECT Get enabled|OBJECT Get enterable|OBJECT GET EVENTS|OBJECT Get filter|'+
'OBJECT Get focus rectangle invisible|OBJECT Get font|OBJECT Get font size|OBJECT Get font style|OBJECT Get format|OBJECT Get help tip|'+
'OBJECT Get horizontal alignment|OBJECT Get indicator type|OBJECT Get keyboard layout|OBJECT Get list name|OBJECT Get list reference|OBJECT GET MAXIMUM VALUE|'+
'OBJECT GET MINIMUM VALUE|OBJECT Get multiline|OBJECT Get name|OBJECT Get placeholder|OBJECT Get plain text|OBJECT Get pointer|OBJECT GET PRINT VARIABLE FRAME|'+
'OBJECT GET RESIZING OPTIONS|OBJECT GET RGB COLORS|OBJECT GET SCROLL POSITION|OBJECT GET SCROLLBAR|OBJECT GET SHORTCUT|OBJECT Get style sheet|OBJECT Get styled text|'+
'OBJECT GET STYLED TEXT ATTRIBUTES|OBJECT GET SUBFORM|OBJECT GET SUBFORM CONTAINER SIZE|OBJECT Get text orientation|OBJECT Get three states checkbox|OBJECT Get title|'+
'OBJECT Get type|OBJECT Get vertical alignment|OBJECT Get visible|OBJECT Is styled text|OBJECT MOVE|OBJECT SET ACTION|OBJECT SET ALIGNMENT|OBJECT SET AUTO SPELLCHECK|'+
'OBJECT SET BORDER STYLE|OBJECT SET CHOICE LIST NAME|OBJECT SET COLOR|OBJECT SET CONTEXT MENU|OBJECT SET COORDINATES|OBJECT SET CORNER RADIUS|OBJECT SET DATA SOURCE|'+
'OBJECT SET DRAG AND DROP OPTIONS|OBJECT SET ENABLED|OBJECT SET ENTERABLE|OBJECT SET EVENTS|OBJECT SET FILTER|OBJECT SET FOCUS RECTANGLE INVISIBLE|OBJECT SET FONT|'+
'OBJECT SET FONT SIZE|OBJECT SET FONT STYLE|OBJECT SET FORMAT|OBJECT SET HELP TIP|OBJECT SET HORIZONTAL ALIGNMENT|OBJECT SET INDICATOR TYPE|OBJECT SET KEYBOARD LAYOUT|'+
'OBJECT SET LIST BY NAME|OBJECT SET LIST BY REFERENCE|OBJECT SET MAXIMUM VALUE|OBJECT SET MINIMUM VALUE|OBJECT SET MULTILINE|OBJECT SET PLACEHOLDER|OBJECT SET PLAIN TEXT|'+
'OBJECT SET PRINT VARIABLE FRAME|OBJECT SET RESIZING OPTIONS|OBJECT SET RGB COLORS|OBJECT SET SCROLL POSITION|OBJECT SET SCROLLBAR|OBJECT SET SHORTCUT|'+
'OBJECT SET STYLE SHEET|OBJECT SET STYLED TEXT|OBJECT SET STYLED TEXT ATTRIBUTES|OBJECT SET SUBFORM|OBJECT SET TEXT ORIENTATION|OBJECT SET THREE STATES CHECKBOX|'+
'OBJECT SET TITLE|OBJECT SET VERTICAL ALIGNMENT|OBJECT SET VISIBLE|Object to path|Old|OLD RELATED MANY|OLD RELATED ONE|On 4D Mobile Authentication database method|'+
'ON ERR CALL|ON EVENT CALL|ONE RECORD SELECT|OPEN 4D PREFERENCES|OPEN ADMINISTRATION WINDOW|OPEN COLOR PICKER|OPEN DATA FILE|OPEN DATABASE|Open document|'+
'Open external window|OPEN FONT PICKER|Open form window|OPEN PRINTING FORM|OPEN PRINTING JOB|Open resource file|OPEN SECURITY CENTER|OPEN SETTINGS WINDOW|'+
'OPEN URL|OPEN WEB URL|Open window|ORDER BY|ORDER BY ATTRIBUTE|ORDER BY FORMULA|ORDER SUBRECORDS BY|OUTPUT FORM|Outside call|PAGE BREAK|PAGE SETUP|Parse formula|'+
'Pasteboard data size|Path to object|PAUSE INDEXES|PAUSE PROCESS|PHP Execute|PHP GET FULL RESPONSE|PHP GET OPTION|PHP SET OPTION|PICTURE CODEC LIST|'+
'PICTURE LIBRARY LIST|PICTURE PROPERTIES|Picture size|PICTURE TO BLOB|PICTURE TO GIF|PICTURE TYPE LIST|PLATFORM PROPERTIES|PLAY|PLUGIN LIST|POP RECORD|'+
'Pop up menu|Position|POST CLICK|POST EVENT|POST KEY|POST OUTSIDE CALL|PREVIOUS PAGE|PREVIOUS RECORD|PREVIOUS SUBRECORD|Print form|PRINT LABEL|Print object|'+
'PRINT OPTION VALUES|PRINT RECORD|PRINT SELECTION|PRINT SETTINGS|Print settings to BLOB|PRINTERS LIST|Printing page|PROCESS 4D TAGS|Process aborted|PROCESS HTML TAGS|'+
'Process number|PROCESS PROPERTIES|Process state|Provide encryption key|PUSH RECORD|QR BLOB TO REPORT|QR Count columns|QR DELETE COLUMN|QR DELETE OFFSCREEN AREA|'+
'QR EXECUTE COMMAND|QR Find column|QR Get area property|QR GET BORDERS|QR Get command status|QR GET DESTINATION|QR Get document property|QR Get drop column|'+
'QR GET HEADER AND FOOTER|QR Get HTML template|QR GET INFO COLUMN|QR Get info row|QR Get report kind|QR Get report table|QR GET SELECTION|QR GET SORTS|'+
'QR Get text property|QR GET TOTALS DATA|QR GET TOTALS SPACING|QR INSERT COLUMN|QR MOVE COLUMN|QR NEW AREA|QR New offscreen area|QR ON COMMAND|QR REPORT|'+
'QR REPORT TO BLOB|QR RUN|QR SET AREA PROPERTY|QR SET BORDERS|QR SET DESTINATION|QR SET DOCUMENT PROPERTY|QR SET HEADER AND FOOTER|QR SET HTML TEMPLATE|'+
'QR SET INFO COLUMN|QR SET INFO ROW|QR SET REPORT KIND|QR SET REPORT TABLE|QR SET SELECTION|QR SET SORTS|QR SET TEXT PROPERTY|QR SET TOTALS DATA|'+
'QR SET TOTALS SPACING|QT COMPRESS PICTURE|QT COMPRESS PICTURE FILE|QT LOAD COMPRESS PICTURE FROM FILE|QUERY|QUERY BY ATTRIBUTE|QUERY BY EXAMPLE|'+
'QUERY BY FORMULA|QUERY BY SQL|QUERY SELECTION|QUERY SELECTION BY ATTRIBUTE|QUERY SELECTION BY FORMULA|QUERY SELECTION WITH ARRAY|QUERY SUBRECORDS|'+
'QUERY WITH ARRAY|QUIT 4D|Random|READ ONLY|Read only state|READ PICTURE FILE|READ WRITE|REAL TO BLOB|RECEIVE BUFFER|RECEIVE PACKET|RECEIVE RECORD|RECEIVE VARIABLE|'+
'Record number|Records in selection|Records in set|Records in subselection|Records in table|REDRAW|REDRAW LIST|REDRAW WINDOW|REDUCE SELECTION|REGENERATE MISSING TABLE|'+
'REGISTER CLIENT|REJECT|RELATE MANY|RELATE MANY SELECTION|RELATE ONE|RELATE ONE SELECTION|RELEASE MENU|RELOAD EXTERNAL DATA|REMOVE FROM SET|REMOVE PICTURE FROM LIBRARY|'+
'Replace string|Request|RESIZE FORM WINDOW|RESOLVE ALIAS|RESOLVE POINTER|RESOURCE LIST|RESOURCE TYPE LIST|RESTART 4D|RESTORE|RESUME INDEXES|RESUME PROCESS|'+
'RESUME TRANSACTION|Right click|Round|SAVE LIST|SAVE PICTURE TO FILE|SAVE RECORD|SAVE RELATED ONE|SAVE SET|SAVE VARIABLES|SAX ADD PROCESSING INSTRUCTION|'+
'SAX ADD XML CDATA|SAX ADD XML COMMENT|SAX ADD XML DOCTYPE|SAX ADD XML ELEMENT VALUE|SAX CLOSE XML ELEMENT|SAX GET XML CDATA|SAX GET XML COMMENT|'+
'SAX GET XML DOCUMENT VALUES|SAX GET XML ELEMENT|SAX GET XML ELEMENT VALUE|SAX GET XML ENTITY|SAX Get XML node|SAX GET XML PROCESSING INSTRUCTION|'+
'SAX OPEN XML ELEMENT|SAX OPEN XML ELEMENT ARRAYS|SAX SET XML DECLARATION|SAX SET XML OPTIONS|SCAN INDEX|SCREEN COORDINATES|SCREEN DEPTH|Screen height|'+
'Screen width|SCROLL LINES|Secured Web connection|Select document|Select folder|SELECT LIST ITEMS BY POSITION|SELECT LIST ITEMS BY REFERENCE|SELECT LISTBOX ROW|'+
'SELECT LOG FILE|Select RGB Color|Selected list items|Selected record number|SELECTION RANGE TO ARRAY|SELECTION TO ARRAY|Selection to JSON|Self|Semaphore|'+
'SEND HTML BLOB|SEND HTML FILE|SEND HTML TEXT|SEND HTTP RAW DATA|SEND HTTP REDIRECT|SEND PACKET|SEND RECORD|SEND SOAP FAULT|SEND VARIABLE|Sequence number|'+
'SET ABOUT|SET ALIGNMENT|SET ALLOWED METHODS|SET ASSERT ENABLED|SET AUTOMATIC RELATIONS|SET BLOB SIZE|SET BLOBS CACHE PRIORITY|SET CACHE SIZE|SET CGI EXECUTABLE|'+
'SET CHANNEL|SET CHOICE LIST|SET COLOR|SET CURRENT PRINTER|SET CURSOR|SET DATABASE LOCALIZATION|SET DATABASE PARAMETER|SET DEFAULT CENTURY|SET DICTIONARY|'+
'SET DOCUMENT CREATOR|SET DOCUMENT POSITION|SET DOCUMENT PROPERTIES|SET DOCUMENT SIZE|SET DOCUMENT TYPE|SET DRAG ICON|SET ENTERABLE|SET ENVIRONMENT VARIABLE|'+
'SET EXTERNAL DATA PATH|SET FIELD RELATION|SET FIELD TITLES|SET FIELD VALUE NULL|SET FILE TO PASTEBOARD|SET FILTER|SET FORM HORIZONTAL RESIZING|SET FORM SIZE|'+
'SET FORM VERTICAL RESIZING|SET FORMAT|Set group properties|SET HOME PAGE|SET HTML ROOT|SET HTTP HEADER|SET INDEX|SET INDEX CACHE PRIORITY|SET LIST ITEM|'+
'SET LIST ITEM FONT|SET LIST ITEM ICON|SET LIST ITEM PARAMETER|SET LIST ITEM PROPERTIES|SET LIST PROPERTIES|SET LISTBOX COLUMN WIDTH|SET LISTBOX GRID COLOR|'+
'SET LISTBOX ROWS HEIGHT|SET LISTBOX TABLE SOURCE|SET MACRO PARAMETER|SET MENU BAR|SET MENU ITEM|SET MENU ITEM ICON|SET MENU ITEM MARK|SET MENU ITEM METHOD|'+
'SET MENU ITEM PARAMETER|SET MENU ITEM PROPERTY|SET MENU ITEM SHORTCUT|SET MENU ITEM STYLE|SET PICTURE FILE NAME|SET PICTURE METADATA|SET PICTURE RESOURCE|'+
'SET PICTURE TO LIBRARY|SET PICTURE TO PASTEBOARD|SET PLATFORM INTERFACE|SET PLUGIN ACCESS|SET PRINT MARKER|SET PRINT OPTION|SET PRINT PREVIEW|SET PRINTABLE MARGIN|'+
'SET PROCESS VARIABLE|SET QUERY AND LOCK|SET QUERY DESTINATION|SET QUERY LIMIT|SET REAL COMPARISON LEVEL|SET RECENT FONTS|SET RESOURCE|SET RESOURCE NAME|'+
'SET RESOURCE PROPERTIES|SET RGB COLORS|SET SCREEN DEPTH|SET SCROLLBAR VISIBLE|SET STRING RESOURCE|SET TABLE CACHE PRIORITY|SET TABLE TITLES|SET TEXT RESOURCE|'+
'SET TEXT TO PASTEBOARD|SET TIMEOUT|SET TIMER|SET UPDATE FOLDER|Set user properties|SET VISIBLE|SET WEB DISPLAY LIMITS|SET WEB SERVICE OPTION|SET WEB SERVICE PARAMETER|'+
'SET WEB TIMEOUT|SET WINDOW RECT|SET WINDOW TITLE|SET XSLT PARAMETER|Shift down|SHOW LISTBOX GRID|SHOW MENU BAR|SHOW ON DISK|SHOW PROCESS|SHOW TOOL BAR|SHOW WINDOW|Sin|'+
'Size of array|SOAP DECLARATION|SOAP Get info|SOAP Request|SOAP SEND FAULT|SORT ARRAY|SORT LIST|SORT LISTBOX COLUMNS|SPELL ADD TO USER DICTIONARY|SPELL CHECK TEXT|'+
'SPELL CHECKING|SPELL Get current dictionary|SPELL GET DICTIONARY LIST|SPELL SET CURRENT DICTIONARY|Split string|SQL CANCEL LOAD|SQL End selection|SQL EXECUTE|'+
'SQL EXECUTE SCRIPT|SQL EXPORT|SQL EXPORT DATABASE|SQL EXPORT SELECTION|SQL GET LAST ERROR|SQL GET OPTION|SQL IMPORT|SQL LOAD RECORD|SQL LOGIN|SQL LOGOUT|'+
'SQL SET OPTION|SQL SET PARAMETER|Square root|ST COMPUTE EXPRESSIONS|ST FREEZE EXPRESSIONS|ST GET ATTRIBUTES|ST Get content type|ST Get expression|ST GET OPTIONS|'+
'ST Get plain text|ST Get text|ST GET URL|ST INSERT EXPRESSION|ST INSERT URL|ST SET ATTRIBUTES|ST SET OPTIONS|ST SET PLAIN TEXT|ST SET TEXT|START SQL SERVER|'+
'START TRANSACTION|START WEB SERVER|Std deviation|STOP SQL SERVER|STOP WEB SERVER|Storage|String|STRING LIST TO ARRAY|Structure file|Substring|Subtotal|Sum|'+
'Sum squares|SUSPEND TRANSACTION|SVG EXPORT TO PICTURE|SVG Find element ID by coordinates|SVG Find element IDs by rect|SVG GET ATTRIBUTE|SVG SET ATTRIBUTE|'+
'SVG SHOW ELEMENT|System folder|Table|Table name|Tan|Temporary folder|Test path name|Test semaphore|TEXT TO ARRAY|TEXT TO BLOB|TEXT TO DOCUMENT|Tickcount|'+
'Time|Time string|Timestamp|Tool bar height|TRACE|Transaction level|TRANSFORM PICTURE|Trigger event|Trigger level|TRIGGER PROPERTIES|True|Trunc|TRUNCATE TABLE|'+
'Type|Undefined|UNION|UNLOAD RECORD|UNREGISTER CLIENT|Uppercase|USE CHARACTER SET|USE ENTITY SELECTION|USE EXTERNAL DATABASE|USE INTERNAL DATABASE|USE NAMED SELECTION|'+
'USE SET|User in group|USERS TO BLOB|Validate Digest Web Password|Validate password|VALIDATE TRANSACTION|Value type|VARIABLE TO BLOB|VARIABLE TO VARIABLE|Variance|'+
'VERIFY CURRENT DATA FILE|VERIFY DATA FILE|Verify password hash|Version type|VOLUME ATTRIBUTES|VOLUME LIST|WA Back URL available|WA Create URL history menu|'+
'WA Evaluate JavaScript|WA Execute JavaScript|WA EXECUTE JAVASCRIPT FUNCTION|WA Forward URL available|WA Get current URL|WA GET EXTERNAL LINKS FILTERS|'+
'WA Get last filtered URL|WA GET LAST URL ERROR|WA Get page content|WA Get page title|WA GET PREFERENCE|WA GET URL FILTERS|WA GET URL HISTORY|WA OPEN BACK URL|'+
'WA OPEN FORWARD URL|WA OPEN URL|WA REFRESH CURRENT URL|WA SET EXTERNAL LINKS FILTERS|WA SET PAGE CONTENT|WA SET PAGE TEXT LARGER|WA SET PAGE TEXT SMALLER|'+
'WA SET PREFERENCE|WA SET URL FILTERS|WA STOP LOADING URL|WEB CACHE STATISTICS|WEB CLOSE SESSION|Web Context|WEB GET BODY PART|WEB Get body part count|'+
'WEB Get Current Session ID|WEB GET HTTP BODY|WEB GET HTTP HEADER|WEB GET OPTION|WEB Get server info|WEB GET SESSION EXPIRATION|WEB Get session process count|'+
'WEB GET STATISTICS|WEB GET VARIABLES|WEB Is secured connection|WEB Is server running|WEB SEND BLOB|WEB SEND FILE|WEB SEND HTTP REDIRECT|WEB SEND RAW DATA|'+
'WEB SEND TEXT|WEB SERVICE AUTHENTICATE|WEB SERVICE CALL|WEB SERVICE Get info|WEB SERVICE GET RESULT|WEB SERVICE SET OPTION|WEB SERVICE SET PARAMETER|'+
'WEB SET HOME PAGE|WEB SET HTTP HEADER|WEB SET OPTION|WEB SET ROOT FOLDER|WEB START SERVER|WEB STOP SERVER|WEB Validate digest|Win to Mac|Window kind|'+
'WINDOW LIST|Window process|Windows Alt down|Windows Ctrl down|WP Add picture|WP CREATE BOOKMARK|WP Create paragraph range|WP Create picture range|WP Create range|'+
'WP Create subsection|WP Create table range|WP DELETE BOOKMARK|WP DELETE FOOTER|WP DELETE HEADER|WP DELETE SUBSECTION|WP EXPORT DOCUMENT|WP EXPORT VARIABLE|'+
'WP GET ATTRIBUTES|WP Get body|WP Get bookmark range|WP GET BOOKMARKS|WP Get element by ID|WP Get elements|WP Get footer|WP Get frame|WP Get header|WP Get page count|'+
'WP Get paragraphs|WP Get pictures|WP Get position|WP Get range|WP Get section|WP Get sections|WP Get selection|WP Get subsection|WP Get text|WP Import document|'+
'WP INSERT BREAK|WP INSERT DOCUMENT|WP INSERT PICTURE|WP Insert table|WP Is font style supported|WP New|WP New footer|WP New header|WP PRINT|WP RESET ATTRIBUTES|'+
'WP SELECT|WP SET ATTRIBUTES|WP SET FRAME|WP SET TEXT|WP Table append row|WP Table get cells|WP Table get columns|WP Table get rows|WP USE PAGE SETUP|'+
'WRITE PICTURE FILE|XML DECODE|XML GET ERROR|XML GET OPTIONS|XML SET OPTIONS|XSLT APPLY TRANSFORMATION|XSLT GET ERROR|XSLT SET PARAMETER|Year of|_o_ADD DATA SEGMENT|'+
'_o_ADD SUBRECORD|_o_ALL SUBRECORDS|_o_AP Get file MD5 digest|_o_APPLY TO SUBSELECTION|_o_ARRAY STRING|_o_ARRAY TO STRING LIST|_o_Before subselection|_o_Convert case|'+
'_o_Create resource file|_o_CREATE SUBRECORD|_o_C_GRAPH|_o_C_INTEGER|_o_C_STRING|_o_DATA SEGMENT LIST|_o_DELETE RESOURCE|_o_DELETE SUBRECORD|_o_DISABLE BUTTON|'+
'_o_Document creator|_o_Document type|_o_During|_o_ENABLE BUTTON|_o_End subselection|_o_FIRST SUBRECORD|_o_Font name|_o_Font number|_o_Gestalt|'+
'_o_Get component resource ID|_o_Get platform interface|_o_GRAPH TABLE|_o_INTEGRATE LOG FILE|_o_INVERT BACKGROUND|_o_ISO to Mac|_o_LAST SUBRECORD|_o_Mac to ISO|'+
'_o_Mac to Win|_o_MAP FILE TYPES|_o_MODIFY SUBRECORD|_o_NEXT SUBRECORD|_o_OBJECT Get action|_o_Open external window|_o_ORDER SUBRECORDS BY|_o_PICTURE TO GIF|'+
'_o_PICTURE TYPE LIST|_o_PLATFORM PROPERTIES|_o_PREVIOUS SUBRECORD|_o_QT COMPRESS PICTURE|_o_QT COMPRESS PICTURE FILE|_o_QT LOAD COMPRESS PICTURE FROM FILE|'+
'_o_QUERY SUBRECORDS|_o_Records in subselection|_o_REDRAW LIST|_o_SAVE PICTURE TO FILE|_o_SET CGI EXECUTABLE|_o_SET DOCUMENT CREATOR|_o_SET DOCUMENT TYPE|'+
'_o_SET PICTURE RESOURCE|_o_SET PLATFORM INTERFACE|_o_SET RESOURCE|_o_SET RESOURCE NAME|_o_SET RESOURCE PROPERTIES|_o_SET STRING RESOURCE|_o_SET TEXT RESOURCE|'+
'_o_SET WEB DISPLAY LIMITS|_o_SET WEB TIMEOUT|_o_USE EXTERNAL DATABASE|_o_USE INTERNAL DATABASE|_o_Web Context|_o_Win to Mac|_o_XSLT APPLY TRANSFORMATION|'+
'_o_XSLT GET ERROR|Char|_o_XSLT SET PARAMETER'

module.exports = command;
