var command = ' 4D a ABORT aborted ABOUT Abs ACCEPT ACCESS ACCUMULATE action Activated Active IN ACTIVITY ADD ADJUST adjusted ADMINISTRATION '+
' After ALERT ALIAS ALIGNMENT ALL ALLOWED Alt APPEND TO AND APP append Application APPLY Arctan AREA ARRAY ARRAYS ASSERT Asserted attribute '+
' ATTRIBUTES AUTHENTICATE Authentication AUTO AUTOMATIC available Average BACK BACKGROUND BACKUP BAR BASE64 BEEP Before Begin BEST '+
' BLOB BLOBS body BOOKMARK BOOKMARKS Bool BOOLEAN border BORDERS BREAK BRING BUFFER BUFFERS BUILD BUTTON BY CACHE calculation call '+
' called CANCEL Caps case CDATA CELL cells CENTER CENTURY CERTIFICATE CERTIFICATES CGI CHANGE CHANNEL Char Character CHECK checkbox '+
' CHECKING child CHOICE Choose CLEAR click Clickcount client CLIENTS CLOSE CODE CODEC COLLAPSE collection collection.length COLOR '+
' COLORS COLUMN COLUMNS Create COMBINE COMMAND COMMENT COMMENTS Compact COMPARISON compiled COMPONENT COMPRESS COMPUTE CONFIRM connection '+
' CONTAINER content Context Contextual control Convert converter COORDINATES COPY CORNER Cos Count CREATE CREATOR Ctrl Current CURSOR '+
' CUT C_BLOB C_BOOLEAN C_COLLECTION C_DATE C_GRAPH C_INTEGER C_LONGINT C_OBJECT C_PICTURE C_POINTER C_REAL C_STRING C_TEXT C_TIME Data '+
' DATABASE Date Day Deactivated Dec DECLARATION DECODE DECRYPT DEFAULT defined DELAY DELETE deleted DEPTH DESCRIBE DESTINATION deviation '+
' DIALOG DICTIONARY DIF DIFFERENCE digest DISABLE DISK DISPLAY Displayed DISTINCT DOCTYPE DOCUMENT DOM down DRAG DROP ds DUPLICATE During '+
' dynamic EDIT edited element elements empty ENABLE ENABLED ENCODE ENCRYPT Encryption End enterable entity ENTRY ENVIRONMENT Equal ERASE '+
' ERR ERROR Euro Evaluate EVENT EVENTS EXAMPLE EXECUTABLE EXECUTE EXECUTION Exp EXPAND EXPIRATION EXPORT EXPRESSION EXPRESSIONS EXTERNAL '+
' False FAULT FIELD FILE FILTER filtered FILTERS Find FIRST FLUSH FOCUS folder FOLDERS Font FONTS FOOTER FOOTERS FORM format FORMATS FORMS '+
' FORMULA FORWARD fragmentation FRAME FREEZE from FRONT Frontmost FULL FUNCTION GENERATE Gestalt Get GIF GOTO GRAPH GRID group hash header '+
' HEADERS height HELP HIDE HIERARCHY HIGHLIGHT HIGHLIGHTED history HOME HORIZONTAL HTML HTTP ICON ID IDLE IDs IMPORT in INDEX indexed INDEXES '+
' indicator info information INPUT INSERT INSTRUCTION Int integer INTEGRATE INTERFACE INTERNAL INTERSECTION INVERT invisible INVOKE Is ISO ITEM '+
' items JavaScript JOB JSON key KEYBOARD KEYPAIR Keystroke KEYWORDS KILL kind LABEL LARGER last LAUNCH LAYOUT LDAP leaks Length level LIBRARY '+
' license LICENSES LIMIT LIMITS line LINES LINKS list LISTBOX LISTS LOAD loaded LOADING LOCALIZATION localized LOCK Locked LOG LOGIN LOGOUT '+
' LONGINT Lowercase Mac machine Macintosh macOS MACRO MAIL MANY MAP MAPPING MARGIN MARK MARKER Match Max MAXIMIZE MAXIMUM MD5 measures MEMORY '+
' menu menus MESSAGE MESSAGES METADATA METHOD METHODS Milliseconds MIME Min MINIMIZE MINIMUM MIRROR MISSING Mobile Mod MODE MODIFICATION Modified '+
' modifiers MODIFY Month mouse MOVE MOVED MULTI MULTILINE name NAMED NAMES New next Nil NO node NODES Not NOTIFICATION NOTIFY NULL Num NUMBER OB '+
' OBJECT OBJECTS ODBC of OFF offscreen OLD on ONE ONLY OPEN OPTION OPTIONS ORDER ORIENTATION OUTPUT Outside owner PACKET PAGE paragraph paragraphs '+
' parameter parameters parent Parse PART Password PASTEBOARD path PATHS PAUSE PHP PICKER PICTURE pictures placeholder array PLAIN plan platform PLAY '+
' PLUGIN pointer pointers pop PORT position POSIX POST PREFERENCE PREFERENCES preview previous PRINT PRINTABLE printed PRINTER PRINTERS PRINTING '+
' priority PROCESS processes PROCESSING PROPERTIES property Provide PUSH QR QT QUERY QUIT radius Random range RAW READ REAL RECEIVE RECENT RECORD '+
' RECORDS RECT rectangle REDIRECT REDRAW REDUCE Ref REFERENCE REFRESH REGENERATE regex REGISTER REGISTERED REJECT RELATE RELATED RELATION RELATIONS '+
' RELEASE RELOAD REMOVE Replace REPORT Request RESET RE Size RESIZING RESOLVE RESOURCE RESOURCES RESPONSE RESTART RESTORE RESULT RESUME Return RGB '+
' Right root Round ROW rows RUN running SAVE SAX SCAN screen screens SCREENSHOT SCRIPT SCROLL SCROLLBAR SEARCH section sections Secured SECURITY '+
' SEGMENT SELECT Selected SELECTION Self semaphore SEND Sequence SERIAL SERVER SERVICE SESSION SESSIONS SET settings SETUP shared sheet SHEETS '+
' Shift SHORTCUT SHOW sibling Sin size SMALLER SNAPSHOT SOAP SORT sorted SORTS source SPACING SPELL SPELLCHECK Split SQL Square squares ST STACK '+
' START state states static STATISTICS status Std STOP Storage STRING String Stringify Structure style STYLED SUBFORM subrecord SUBRECORDS subsection '+
' SUBSELECTION Substring Subtotal Sum supported SUSPEND SVG SYLK system TABLE TAGS Tan tasks template Temporary Test TEXT This THREE THUMBNAIL '+
' Tickcount TIME TIMEOUT TIMER Timestamp TIP TITLE TITLES to TOOL TOTALS TRACE TRANSACTION TRANSFORM TRANSFORMATION TRIGGER True Trunc TRUNCATE '+
' type TYPES Undefined UNION UNLOAD UNREGISTER up update Uppercase URL USE user USERS UUID valid Validate VALUE VALUES VAR VARIABLE VARIABLES '+
' Variance Verify Version VERTICAL View visible VOLUME WA waiting WEB WIDTH Win WINDOW Windows WITH WORKER WP WRITE XML XSLT XY Year _o_ADD '+
' _o_ALL _o_AP _o_APPLY _o_ARRAY _o_Before _o_Convert _o_CREATE _o_C_GRAPH _o_C_INTEGER _o_C_STRING _o_DATA _o_DELETE _o_DISABLE _o_Document '+
' _o_During _o_ENABLE _o_End _o_FIRST _o_Font _o_Gestalt _o_Get _o_GRAPH _o_INTEGRATE _o_INVERT _o_ISO _o_LAST _o_Mac _o_MAP _o_MODIFY _o_NEXT '+
' _o_OBJECT _o_Open _o_ORDER _o_PICTURE _o_PLATFORM _o_PREVIOUS _o_QT _o_QUERY _o_Records _o_REDRAW _o_SAVE _o_SET _o_USE _o_Web _o_Win _o_XSLT '

module.exports = command;
