var plugin = 'PV GET BORDER ROW RANGES|4d_function_call|4d_language_reference|ABS|ACOS|all_or_any_predicate|ALTER SCHEMA|ALTER TABLE|AP AVAILABLE MEMORY|'+
'AP BLOB to print settings|AP CLOSE HELP|AP Create method|AP Does method exist|AP FCLOSE|AP fopen|AP FPRINT|AP fread|AP FULL SCREEN|AP Get field infos|'+
'AP Get file MD5 digest|AP GET PARAM|AP Get picture type|AP Get table info|AP Get templates|AP Get tips state|AP HELP INDEX|AP HELP ON HELP|AP HELP ON KEY|'+
'AP Is Picture Deprecated|AP Modify method|AP NORMAL SCREEN|AP Print settings to BLOB|AP Rect dragger|AP Save BMP 8 bits|AP SET CLOCK|AP SET PARAM|AP SET TIPS STATE|'+
'AP ShellExecute|AP Timestamp to GMT|arithmetic_expression|ASCII|ASIN|ATAN|ATAN2|AVG|between_predicate|BIT_LENGTH|case_expression|CAST|CEILING|CHAR|CHAR_LENGTH|COALESCE|'+
'collection.average( )|collection.clear( )|collection.combine( )|collection.concat( )|collection.count( )|collection.countValues( )|collection.distinct( )|'+
'collection.equal( )|collection.every( )|collection.extract( )|collection.fill( )|collection.filter( )|collection.find( )|collection.findIndex( )|collection.indexOf( )|'+
'collection.indices( )|collection.join( )|collection.lastIndexOf( )|collection.map( )|collection.max( )|collection.min( )|collection.orderBy( )|'+
'collection.orderByMethod( )|collection.pop( )|collection.push( )|collection.query( )|collection.reduce( )|collection.remove( )|collection.resize( )|'+
'collection.reverse( )|collection.shift( )|collection.slice( )|collection.some( )|collection.sort( )|collection.sum( )|column_definition|column_reference|'+
'command_parameter|COMMIT|comparison_predicate|CONCAT|CONCATENATE|COS|COT|COUNT|CREATE INDEX|CREATE SCHEMA|CREATE TABLE|CT ALIGN|CT AREA TO AREA|CT AREA TO FIELD|'+
'CT Area to picture|CT Array to polygon|CT Chart arrays|CT Chart data|CT Chart selection|CT Clipboard to picture|CT Color to index|CT COLOR TO RGB|CT Count|'+
'CT DELETE OFFSCREEN AREA|CT DO COMMAND|CT Draw line|CT Draw oval|CT Draw rectangle|CT Draw text|CT Error|CT EVENT FILTER|CT EXPERT COMMAND|CT EXPERT MODE|'+
'CT EXPLODE PIE|CT FIELD TO AREA|CT Font name|CT Font number|CT GET 3D VIEW|CT GET AREA BOUNDARY|CT GET AREA PROPERTY|CT GET AXIS ATTRIBUTES|CT GET BOUNDARY|'+
'CT GET CHART COORDINATES|CT GET CHART FILL ATTRIBUTES|CT GET CHART LINE ATTRIBUTES|CT GET CHART OPTIONS|CT GET CHART PART|CT Get chart picture|'+
'CT GET CHART TEXT ATTRIBUTES|CT Get chart type|CT GET DATE SCALE|CT GET DEPTH|CT Get display|CT GET DOCUMENT SIZE|CT GET FILL ATTRIBUTES|CT GET HIGHLIGHT|'+
'CT Get ID|CT GET LABEL ATTRIBUTES|CT GET LEGEND ATTRIBUTES|CT Get legend text|CT GET LINE ATTRIBUTES|CT Get object type|CT GET PROPERTIES|CT GET REAL SCALE|'+
'CT Get refnum|CT GET TEXT ATTRIBUTES|CT GET TIPS ATTRIBUTES|CT GET TITLE ATTRIBUTES|CT GET VALUE ATTRIBUTES|CT GET X DATE SCALE|CT GET X REAL SCALE|'+
'CT Index to color|CT INSERT EXPRESSION|CT INSERT FIELD|CT Last event|CT MENU STATUS|CT MOVE|CT NEW DOCUMENT|CT New offscreen area|CT ON ERROR|CT ON EVENT|'+
'CT ON MENU|CT OPEN DOCUMENT|CT PICTURE TO AREA|CT PICTURE TO CLIPBOARD|CT Place picture|CT PRINT|CT PRINT MERGE|CT RGB to color|CT SAVE DOCUMENT|CT SELECT|'+
'CT SET 3D VIEW|CT SET AREA PROPERTY|CT SET AXIS ATTRIBUTES|CT SET CHART COORDINATES|CT SET CHART FILL ATTRIBUTES|CT SET CHART LINE ATTRIBUTES|CT SET CHART OPTIONS|'+
'CT SET CHART PICTURE|CT SET CHART TEXT ATTRIBUTES|CT SET CHART TYPE|CT SET DATE SCALE|CT SET DEPTH|CT SET DISPLAY|CT SET DOCUMENT SIZE|CT SET ENTERABLE|'+
'CT SET FILL ATTRIBUTES|CT SET FILLS ATTRIBUTES|CT SET HIGHLIGHT|CT SET LABEL ATTRIBUTES|CT SET LEGEND ATTRIBUTES|CT SET LEGEND TEXT|CT SET LINE ATTRIBUTES|'+
'CT SET LINES ATTRIBUTES|CT SET PROPERTIES|CT SET REAL SCALE|CT SET REFNUM|CT SET TEXT ATTRIBUTES|CT SET TIPS ATTRIBUTES|CT SET TITLE ATTRIBUTES|'+
'CT SET VALUE ATTRIBUTES|CT SET X DATE SCALE|CT SET X REAL SCALE|CT SHOW GRID LINES|CT SIZE|CT UPDATE CHART|CURDATE|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|'+
'CURTIME|DATE_TO_CHAR|DAY|DAYNAME|DAYOFMONTH|DAYOFWEEK|DAYOFYEAR|DEGREES|DELETE|DROP INDEX|DROP SCHEMA|DROP TABLE|EXECUTE IMMEDIATE|exists_predicate|EXP|'+
'EXPORT STRUCTURE|EXTRACT|FLOOR|foreign_key_definition|formula.apply( )|FTP_Append|FTP_ChangeDir|FTP_Delete|FTP_GetDirList|FTP_GetFileInfo|FTP_GetPassive|'+
'FTP_GetType|FTP_Login|FTP_Logout|FTP_MacBinary|FTP_MakeDir|FTP_PrintDir|FTP_Progress|FTP_Receive|FTP_RemoveDir|FTP_Rename|FTP_Send|FTP_SetPassive|FTP_SetType|'+
'FTP_System|FTP_VerifyID|function_call|GRANT|HOUR|IMAP_Capability|IMAP_CloseCurrentMB|IMAP_CopyToMB|IMAP_CreateMB|IMAP_Delete|IMAP_DeleteMB|IMAP_Download|'+
'IMAP_GetCurrentMB|IMAP_GetFlags|IMAP_GetMBStatus|IMAP_GetMessage|IMAP_GetPrefs|IMAP_ListMBs|IMAP_Login|IMAP_Logout|IMAP_MsgFetch|IMAP_MsgInfo|IMAP_MsgLst|'+
'IMAP_MsgLstInfo|IMAP_MsgNumToUID|IMAP_RenameMB|IMAP_Search|IMAP_SetCurrentMB|IMAP_SetFlags|IMAP_SetPrefs|IMAP_SubscribeMB|IMAP_UIDToMsgNum|IMAP_VerifyID|'+
'IMPORT STRUCTURE|in_predicate|is_null_predicate|IT_Decode|IT_Encode|IT_ErrorText|IT_GetPort|IT_GetProxy|IT_GetTimeOut|IT_MacTCPInit|IT_MacTCPVer|'+
'IT_MyTCPAddr|IT_Platform|IT_PPPConnect|IT_PPPDisconnect|IT_PPPStatus|IT_SetPort|IT_SetProxy|IT_SetTimeOut|IT_TCPversion|IT_Version|LEFT|LENGTH|like_predicate|'+
'literal|LOCATE|LOCK TABLE|LOG|LOG10|LOWER|LTRIM|MAX|MILLISECOND|MIN|MINUTE|MOD|MONTH|MONTHNAME|MSG_Charset|MSG_Delete|MSG_Extract|MSG_FindHeader|MSG_GetBody|'+
'MSG_GetHeaders|MSG_GetMessage|MSG_GetPrefs|MSG_HasAttach|MSG_MessageSize|MSG_SetPrefs|NET_AddrToName|NET_Finger|NET_NameToAddr|NET_Ping|NET_Resolve|NET_Time|NULLIF|'+
'OCIAttrGetText|OCIAttrGetVal|OCIAttrSetText|OCIAttrSetVal|OCIBindByName|OCIBindByPos|OCIBindDateByName|OCIBindDateByPos|OCIBreak|OCICacheFlush|OCICacheFree|'+
'OCICacheRefresh|OCICacheUnmark|OCICacheUnpin|OCICollAppend|OCICollAssign|OCICollAssignElem|OCICollGetElem|OCICollMax|OCICollSize|OCICollTrim|OCIDateAddDays|'+
'OCIDateAddMonths|OCIDateFromText|OCIDateLastDay|OCIDateNextDay|OCIDateSysDate|OCIDateToText|OCIDateZoneToZone|OCIDefineByPos|OCIDefineDateByPos|OCIDescribeAnyText|'+
'OCIDescribeAnyVal|OCIDescriptorAlloc|OCIDescriptorFree|OCIDurationBegin|OCIDurationEnd|OCIEnvCreate|OCIErrorGet|OCIGetTnsnamesPath|OCIHandleAlloc|OCIHandleFree|'+
'OCIIterCreate|OCIIterDelete|OCIIterGetCurrent|OCIIterInit|OCIIterNext|OCIIterPrev|OCILobAppend|OCILobAssign|OCILobCharSetForm|OCILobCharSetId|OCILobCopy|'+
'OCILobCreateTemporary|OCILobDisableBuffering|OCILobEnableBuffering|OCILobErase|OCILobFileClose|OCILobFileCloseAll|OCILobFileExists|OCILobFileGetName|OCILobFileIsOpen|'+
'OCILobFileOpen|OCILobFileSetName|OCILobFlushBuffer|OCILobFreeTemporary|OCILobGetChunkSize|OCILobGetLength|OCILobIsEqual|OCILobIsTemporary|OCILobLoadFromFile|'+
'OCILobLocatorIsInit|OCILobRead|OCILobTrim|OCILobWrite|OCILobWriteAppend|OCILogoff|OCILogon|OCINumberAdd|OCINumberArcCos|OCINumberArcSin|OCINumberArcTan|OCINumberArcTan2|'+
'OCINumberCos|OCINumberDiv|OCINumberExp|OCINumberFromText|OCINumberHypCos|OCINumberHypSin|OCINumberHypTan|OCINumberIntPower|OCINumberLn|OCINumberLog|OCINumberMul|'+
'OCINumberPower|OCINumberRound|OCINumberSin|OCINumberSqrt|OCINumberSub|OCINumberTan|OCINumberToText|OCINumberTrunc|OCIOnErrCall|OCIParamGet|OCIParamSet|OCIPasswordChange|'+
'OCIRawAllocSize|OCIRawAssignBytes|OCIRawAssignRaw|OCIRawPtr|OCIRawResize|OCIRawSize|OCIRefAssign|OCIRefClear|OCIRefFromHex|OCIRefHexSize|OCIRefIsEqual|OCIRefIsNull|'+
'OCIRefToHex|OCIReset|OCIServerAttach|OCIServerDetach|OCIServerVersion|OCISessionBegin|OCISessionEnd|OCIStmtExecute|OCIStmtFetch|OCIStmtGetBindInfo|OCIStmtPrepare|'+
'OCITableDelete|OCITableExists|OCITableFirst|OCITableLast|OCITableNext|OCITablePrev|OCITableSize|OCITerminate|OCITransCommit|OCITransDetach|OCITransForget|'+
'OCITransPrepare|OCITransRollback|OCITransStart|OCTET_LENGTH|ODBC_LenDataAtExec|ODBC_SetErrorHandler|ODBC_SQLAllocConnect|ODBC_SQLAllocStmt|ODBC_SQLBindCol|'+
'ODBC_SQLBindParameter|ODBC_SQLBrowseConnect|ODBC_SQLBulkOperations|ODBC_SQLCancel|ODBC_SQLCloseCursor|ODBC_SQLColAttribute|ODBC_SQLColumnPrivileges|ODBC_SQLColumns|'+
'ODBC_SQLConnect|ODBC_SQLDataSources|ODBC_SQLDescribeCol|ODBC_SQLDescribeParam|ODBC_SQLDisconnect|ODBC_SQLDriverConnect|ODBC_SQLDrivers|ODBC_SQLEndTran|'+
'ODBC_SQLExecDirect|ODBC_SQLExecute|ODBC_SQLFetch|ODBC_SQLFetchScroll|ODBC_SQLForeignKeys|ODBC_SQLFreeConnect|ODBC_SQLFreeStmt|ODBC_SQLGetConnectAttr|'+
'ODBC_SQLGetCursorName|ODBC_SQLGetData|ODBC_SQLGetDescField|ODBC_SQLGetDescRec|ODBC_SQLGetDiagField|ODBC_SQLGetDiagRec|ODBC_SQLGetEnvAttr|ODBC_SQLGetFunctions|'+
'ODBC_SQLGetInfo|ODBC_SQLGetStmtAttr|ODBC_SQLGetTypeInfo|ODBC_SQLMoreResults|ODBC_SQLNativeSql|ODBC_SQLNumParams|ODBC_SQLNumResultCols|ODBC_SQLParamData|ODBC_SQLPrepare|'+
'ODBC_SQLPrimaryKeys|ODBC_SQLProcedureColumns|ODBC_SQLProcedures|ODBC_SQLPutData|ODBC_SQLRowCount|ODBC_SQLSetConnectAttr|ODBC_SQLSetCursorName|ODBC_SQLSetDescField|'+
'ODBC_SQLSetDescRec|ODBC_SQLSetEnvAttr|ODBC_SQLSetPos|ODBC_SQLSetStmtAttr|ODBC_SQLSpecialColumns|ODBC_SQLStatistics|ODBC_SQLTablePrivileges|ODBC_SQLTables|OLE_DEL OBJECT|'+
'OLE_EXEC ACTION|OLE_GET OBJECT RECT|OLE_INS DIALOG|OLE_Insert file|On Exit database method|On Server Open Connection database method|PI|POP3_BoxInfo|POP3_Charset|'+
'POP3_Delete|POP3_DownLoad|POP3_GetMessage|POP3_GetPrefs|POP3_Login|POP3_Logout|POP3_MsgInfo|POP3_MsgLst|POP3_MsgLstInfo|POP3_Reset|POP3_SetPrefs|POP3_UIDToNum|'+
'POP3_VerifyID|POSITION|POWER|predicate|primary_key_definition|PV ADD DYNAMIC ARRAYS|PV ADD DYNAMIC FIELDS|PV Add font|PV Add format|PV ADD HOR SPLITTER|PV Add picture|'+
'PV Add style|PV ADD VERT SPLITTER|PV Area to blob|PV ARRAY TO CELLS|PV BLOB TO AREA|PV BLOB TO PRINT SETTINGS|PV CELLS TO ARRAY|PV CLEAR DYNAMIC COLUMNS|'+
'PV Color to index|PV COLOR TO RGB|PV Copy to blob|PV Create picture|PV DELETE CELLS|PV DELETE COLUMNS|PV DELETE OFFSCREEN AREA|PV DELETE ROWS|PV EXECUTE COMMAND|'+
'PV EXPORT|PV FIELD TO CELLS|PV FIELDS LIST TO CELLS|PV FIND ALL|PV FIND ONE|PV FREEZE PANES|PV GET ALLOWED COM LIST|PV GET ALLOWED MET LIST|PV GET ALLOWED VAR LIST|'+
'PV Get area property|PV GET BORDER COLUMN RANGES|PV GET BORDER STYLE|PV Get cell boolean value|PV GET CELL CONTROL|PV GET CELL DATE TIME VALUE|PV Get cell date value|'+
'PV GET CELL FIELD|PV Get cell formula|PV Get cell name|PV GET CELL NAME LIST|PV Get cell num value|PV Get cell picture value|PV Get cell property|'+
'PV Get cell string value|PV Get cell text value|PV Get cell time value|PV Get cell value type|PV Get cell variable|PV GET COLUMN HEADER|PV Get column width|'+
'PV GET COMMAND STATUS|PV GET CURRENT CELL|PV GET DOCUMENT INFO|PV Get document property|PV GET DRAG SIGNATURES|PV GET DRAG SOURCE|PV Get drop info|'+
'PV GET DROP SIGNATURES|PV GET DROP TARGET|PV GET FONT LIST|PV GET FORMAT LIST|PV Get header|PV Get hor pane property|PV GET LAST ERROR|PV GET NEXT FREE CELL|'+
'PV Get on command method|PV Get on error method|PV Get on event method|PV Get picture|PV Get picture property|PV Get plugin property|PV GET PREVIOUS ACTIVE CELL|'+
'PV Get print property|PV Get range property|PV Get row header|PV Get row height|PV GET SELECTED RANGES LIST|PV GET STYLE LIST|PV Get style property|'+
'PV Get vert pane property|PV Get window title|PV GOTO CELL|PV GOTO NEXT CELL|PV Index to color|PV INSERT CELLS|PV INSERT COLUMNS|PV INSERT ROWS|PV Is all selected|'+
'PV Is cell selected|PV Is column selected|PV Is range selected|PV Is row selected|PV New offscreen area|PV ON COMMAND|PV ON ERROR|PV ON EVENT|PV OPEN DOCUMENT|'+
'PV PASTE FROM BLOB|PV PRINT|PV PRINT FORMULAS|PV Print settings to blob|PV REDRAW|PV REMOVE FONT|PV REMOVE FORMAT|PV REMOVE HOR SPLITTER|PV REMOVE PICTURE|'+
'PV REMOVE STYLE|PV REMOVE VERT SPLITTER|PV REPLACE ALL|PV REPLACE ONE|PV REPORT MANY|PV REPORT ONE|PV RGB to color|PV SAVE DOCUMENT|PV SCROLL AREA|PV SELECT ALL|'+
'PV SELECT CELL|PV SELECT COLUMNS|PV SELECT RANGE|PV SELECT RANGES LIST|PV SELECT ROWS|PV SET ALLOWED COM LIST|PV SET ALLOWED MET LIST|PV SET ALLOWED VAR LIST|'+
'PV SET AREA PROPERTY|PV SET BORDER STYLE|PV SET CELL BOOLEAN VALUE|PV SET CELL CONTROL|PV SET CELL DATE TIME VALUE|PV SET CELL DATE VALUE|PV SET CELL FIELD|'+
'PV SET CELL FORMULA|PV SET CELL NAME|PV SET CELL NUM VALUE|PV SET CELL PICTURE VALUE|PV SET CELL PROPERTY|PV SET CELL STRING VALUE|PV SET CELL TEXT VALUE|'+
'PV SET CELL TIME VALUE|PV SET CELL VARIABLE|PV SET COLUMN HEADER|PV SET COLUMNS WIDTH|PV SET COMMAND STATUS|PV SET DOCUMENT INFO|PV SET DOCUMENT PROPERTY|'+
'PV SET DRAG SIGNATURES|PV SET DROP SIGNATURES|PV SET FORMAT|PV SET HEADER|PV SET HOR PANE PROPERTY|PV SET PICTURE PROPERTY|PV SET PLUGIN PROPERTY|'+
'PV SET PRINT PROPERTY|PV SET RANGE BORDER|PV SET RANGE PROPERTY|PV SET ROW HEADER|PV SET ROWS HEIGHT|PV SET STYLE NAME|PV SET STYLE PROPERTY|PV SET VERT PANE PROPERTY|'+
'PV SET WINDOW TITLE|PV SORT COLUMN|PV SORT MANY|PV SORT ONE|PV SPECIAL CLEAR|PV SPECIAL CUT|PV SPECIAL PASTE|PV UNFREEZE PANES|PV UPDATE DYNAMIC AREA|'+
'PV VALIDATE CURRENT CELL|QUARTER|RADIANS|RAND|REPEAT|REPLACE|REVOKE|RIGHT|ROLLBACK|ROUND|RTRIM|search_condition|SECOND|SELECT|select_item|SIGN|SIN|SMTP_AddHeader|'+
'SMTP_Attachment|SMTP_Auth|SMTP_Bcc|SMTP_Body|SMTP_Cc|SMTP_Charset|SMTP_Clear|SMTP_Comments|SMTP_Date|SMTP_Encrypted|SMTP_From|SMTP_GetPrefs|SMTP_Host|SMTP_InReplyTo|'+
'SMTP_Keywords|SMTP_New|SMTP_QuickSend|SMTP_References|SMTP_ReplyTo|SMTP_Send|SMTP_Sender|SMTP_SetPrefs|SMTP_Subject|SMTP_To|sort_list|SPACE|sql_data_type_name|sql_name|'+
'sql_string|SQRT|START|subquery|SUBSTRING|SUM|SVGTool_SET_VIEWER_CALLBACK|SVGTool_SHOW_IN_VIEWER|SVG_ABOUT|SVG_ADD_NAMESPACE|SVG_Add_object|SVG_ADD_POINT|'+
'SVG_APPEND_TEXT_TO_TEXTAREA|SVG_CLEAR|SVG_Color_from_index|SVG_Color_grey|SVG_Color_RGB_from_CMYK|SVG_Color_RGB_from_HLS|SVG_Color_RGB_from_long|SVG_Copy|'+
'SVG_Count_elements|SVG_Define_clip_path|SVG_Define_filter|SVG_Define_linear_gradient|SVG_Define_marker|SVG_Define_pattern|SVG_Define_radial_gradient|SVG_Define_shadow|'+
'SVG_Define_solidColor|SVG_Define_style|SVG_DEFINE_STYLE_WITH_ARRAYS|SVG_Define_symbol|SVG_DELETE_OBJECT|SVG_ELEMENTS_TO_ARRAYS|SVG_Estimate_weight|SVG_Export_to_picture|'+
'SVG_Export_to_XML|SVG_FADE_TO_GREY_SCALE|SVG_Filter_Blend|SVG_Filter_Blur|SVG_Filter_Offset|SVG_Find_ID|SVG_GET_ATTRIBUTES|SVG_GET_COLORS_ARRAY|SVG_GET_DEFAULT_BRUSHES|'+
'SVG_Get_default_encoding|SVG_Get_ID|SVG_Get_options|SVG_Get_root_reference|SVG_Get_text|SVG_Get_version|SVG_Is_reference_valid|SVG_New|SVG_New_arc|SVG_New_circle|'+
'SVG_New_ellipse|SVG_New_ellipse_bounded|SVG_New_embedded_image|SVG_New_group|SVG_New_image|SVG_New_line|SVG_New_path|SVG_New_polygon|SVG_New_polygon_by_arrays|'+
'SVG_New_polyline|SVG_New_polyline_by_arrays|SVG_New_rect|SVG_New_regular_polygon|SVG_New_text|SVG_New_textArea|SVG_New_tspan|SVG_New_vertical_text|SVG_Open_file|'+
'SVG_Open_picture|SVG_PATH_ARC|SVG_PATH_CLOSE|SVG_PATH_CURVE|SVG_PATH_LINE_TO|SVG_PATH_MOVE_TO|SVG_PATH_QCURVE|SVG_Post_comment|SVG_Read_element_type|SVG_Read_last_error|'+
'SVG_References_array|SVG_SAVE_AS_PICTURE|SVG_SAVE_AS_TEXT|SVG_SET_ATTRIBUTES|SVG_SET_ATTRIBUTES_BY_ARRAYS|SVG_SET_CLASS|SVG_SET_CLIP_PATH|SVG_SET_DEFAULT_BRUSHES|'+
'SVG_SET_DEFAULT_ENCODING|SVG_Set_description|SVG_SET_DIMENSIONS|SVG_SET_DOCUMENT_VARIABLE|SVG_Set_error_handler|SVG_SET_FILL_BRUSH|SVG_SET_FILL_RULE|SVG_SET_FILTER|'+
'SVG_SET_FONT_COLOR|SVG_SET_FONT_FAMILY|SVG_SET_FONT_SIZE|SVG_SET_FONT_STYLE|SVG_SET_HUE|SVG_SET_ID|SVG_SET_MARKER|SVG_SET_OPACITY|SVG_SET_OPTIONS|'+
'SVG_SET_PATTERN_CONTENT_UNITS|SVG_SET_PATTERN_UNITS|SVG_SET_ROUNDING_RECT|SVG_SET_SATURATION|SVG_SET_SHAPE_RENDERING|SVG_SET_STROKE_BRUSH|SVG_SET_STROKE_DASHARRAY|'+
'SVG_SET_STROKE_LINECAP|SVG_SET_STROKE_LINEJOIN|SVG_SET_STROKE_MITERLIMIT|SVG_SET_STROKE_WIDTH|SVG_SET_TEXTAREA_TEXT|SVG_SET_TEXT_ANCHOR|SVG_SET_TEXT_KERNING|'+
'SVG_SET_TEXT_LETTER_SPACING|SVG_SET_TEXT_RENDERING|SVG_SET_TEXT_WRITING_MODE|SVG_Set_title|SVG_SET_TRANSFORM_FLIP|SVG_SET_TRANSFORM_MATRIX|SVG_SET_TRANSFORM_ROTATE|'+
'SVG_SET_TRANSFORM_SCALE|SVG_SET_TRANSFORM_SKEW|SVG_SET_TRANSFORM_TRANSLATE|SVG_SET_VIEWBOX|SVG_SET_VIEWPORT_FILL|SVG_SET_VISIBILITY|SVG_SET_XY|SVG_Use|SVG_Validate_file|'+
'table_constraint|table_reference|TAN|TCP_Close|TCP_Listen|TCP_Open|TCP_Receive|TCP_ReceiveBLOB|TCP_Send|TCP_SendBLOB|TCP_State|Transactions|TRANSLATE|TRIM|TRUNC|'+
'TRUNCATE|UDP_Delete|UDP_New|UDP_ReceiveBLOBFrom|UDP_ReceiveFrom|UDP_SendBLOBTo|UDP_SendTo|UNLOCK TABLE|UPDATE|UPPER|VP Convert from 4D View|WEEK|WP GET BOOKMARKS|'+
'WP INSERT BREAK|WR ADD STYLESHEET TAB|WR ADD TAB|WR APPLY STYLESHEET|WR Area to blob|WR Area to picture|WR BACKSPACE|WR BLOB TO AREA|WR BLOB TO PRINT SETTINGS|'+
'WR Build preview|WR COLOR TO RGB|WR Count|WR Create stylesheet|WR DELETE OFFSCREEN AREA|WR DELETE PICTURE IN PAGE|WR DELETE SELECTION|WR DELETE STYLESHEET|'+
'WR DELETE STYLESHEET TAB|WR DELETE TAB|WR Direct find|WR Error number|WR Error text|WR EXECUTE COMMAND|WR Find|WR FONTS TO ARRAY|WR GET AREA PROPERTY|'+
'WR GET COMMAND INFO|WR GET CURSOR COORDINATES|WR GET CURSOR POSITION|WR GET DATE AND TIME FORMAT|WR Get doc property|WR GET DOCUMENT INFO|WR GET DRAG SOURCE|'+
'WR GET DROP INFO|WR GET DROP TARGET|WR Get font|WR Get frame|WR Get HTML expression|WR GET HYPERLINK|WR Get on command method|WR Get on error method|'+
'WR Get on event method|WR GET PAGE NUMBER FORMAT|WR GET PARAGRAPHS|WR GET PICTURE IN PAGE INFO|WR GET PICTURE SIZE|WR GET PRINT OPTION|WR GET REFERENCE|'+
'WR Get RTF expression|WR Get selected picture|WR Get selected text|WR GET SELECTION|WR Get styled text|WR Get stylesheet font|WR GET STYLESHEET INFO|'+
'WR GET STYLESHEET TAB|WR Get stylesheet text prop|WR GET TAB|WR Get text|WR Get text property|WR GET WORDS|WR INSERT DATE AND TIME|WR INSERT EXPRESSION|'+
'WR INSERT FIELD|WR INSERT HTML EXPRESSION|WR INSERT HYPERLINK|WR INSERT PAGE NUMBER|WR INSERT PICTURE|WR Insert picture area|WR INSERT RTF EXPRESSION|'+
'WR INSERT STYLED TEXT|WR INSERT TEXT|WR LOCK COMMAND|WR LOCK DOCUMENT|WR Mouse to selection|WR New offscreen area|WR ON COMMAND|WR ON ERROR|WR ON EVENT|'+
'WR OPEN DOCUMENT|WR PICTURE TO AREA|WR PRINT|WR PRINT MERGE|WR Print settings to BLOB|WR REDRAW|WR Replace|WR RGB to color|WR SAVE DOCUMENT|WR SCROLL TO SELECTION|'+
'WR SELECT|WR SELECT PICTURE IN PAGE|WR SET AREA PROPERTY|WR SET CURSOR POSITION|WR SET DOC PROPERTY|WR SET DOCUMENT INFO|WR SET FONT|WR SET FRAME|'+
'WR SET PICTURE IN PAGE INFO|WR SET PICTURE SIZE|WR SET PRINT OPTION|WR SET SELECTION|WR SET STYLESHEET FONT|WR SET STYLESHEET INFO|WR SET STYLESHEET TAB|'+
'WR SET STYLESHEET TEXT PROP|WR SET TAB|WR SET TEXT PROPERTY|WR TEXT ACCESS|WR UPDATE MODE|WR UPDATE STYLESHEET|YEAR|_AP External clock|_o_AP BLOB to print settings|'+
'_o_AP FCLOSE|_o_AP fopen|_o_AP FPRINT|_o_AP fread|_o_AP FULL SCREEN|_o_AP Get field infos|_o_AP Get table info|_o_AP Get tips state|_o_AP Is Picture Deprecated|'+
'_o_AP NORMAL SCREEN|_o_AP Print settings to BLOB|_o_AP Save BMP 8 bits|_o_AP SET TIPS STATE|_o_AP ShellExecute|_o_OCICleanUp'

module.exports = plugin;